In [29]:
import mybfgs as mb
import numpy as np
import scipy

In [21]:
#example functions:
def sumofexp(x):
    t = np.linspace(0.1,1.0,10)
    return np.sum((np.e**(-x[0]*t)-np.e**(-x[1]*t)-np.e**(-t)+np.e**(-10*t))**2)

def Rosenbrock(x):
    return 100*(x[1]**2-2*x[1]*x[0]**2+x[0]**4)+(1-2*x[0]+x[0]**2)

def Wood(x):
    x1 = x[0]
    x2 = x[1]
    x3 = x[2]
    x4 = x[3]
    return 100*(x2-x1**2)**2+(1-x1)**2+90*(x4-x3**2)**2\
            +(1-x3)**2+10.1*((x2-1)**2+(x4-1)**2)+19.8*(x2-1)*(x4-1)

def Weibull(x):
    y = np.linspace(0.0,0.99,99)
    y = np.delete(y,[0])
    x0 = np.array([50.0,1.5,25.0])
    t = np.zeros(np.size(y))
    for i in range(0,np.size(y)):
        t[i]=(-x0[0]*np.log(y[i]))**(1/x0[1])+x0[2]
    return np.sum((np.e**(-(1/x[0])*np.sign(t-x[2])*(abs(t-x[2]))**x[1])-y)**2)

def ExtendedRb(x):
    n = np.size(x)
    sums = 0
    for i in range(int(n/2)):
        sums += 100*(x[2*i]**2-2*x[2*i]*x[2*i-1]**2+x[2*i-1]**4)+(1-2*x[2*i-1]+x[2*i-1]**2)
    return sums

In [22]:
#sum of exponentials
xs = np.zeros((5,2))
xs[0,:] = np.array([5.0,0.0])
xs[1,:] = np.array([0.0,0.0])
xs[2,:] = np.array([0.0,20.0])
xs[3,:] = np.array([2.5,10.0])
xs[4,:] = np.array([5.0,20.0])

for i in range(5):
    x = xs[i,:]
    print(f'initial point: x0 = {x}')
    print(f'my BFGS: ')
    print(f'x: {mb.BFGS(sumofexp,x)[0]}, iterations: {mb.BFGS(sumofexp,x)[1]}')
    print(f'SciPy BFGS: ')
    print(scipy.optimize.minimize(sumofexp, x, method='BFGS'))
    print(f'SciPy L-BFGS: ')
    print(scipy.optimize.minimize(sumofexp, x, method='L-BFGS-B'))

initial point: x0 = [5. 0.]
my BFGS: 
x: [ 1.00000004 10.00001392], iterations: 13
SciPy BFGS: 
  message: Optimization terminated successfully.
  success: True
   status: 0
      fun: 2.933535839270707e-14
        x: [ 1.000e+00  1.000e+01]
      nit: 21
      jac: [-1.729e-07 -9.652e-09]
 hess_inv: [[ 6.305e-01  3.843e+00]
            [ 3.843e+00  2.323e+02]]
     nfev: 78
     njev: 26
SciPy L-BFGS: 
  message: CONVERGENCE: NORM_OF_PROJECTED_GRADIENT_<=_PGTOL
  success: True
   status: 0
      fun: 2.985519741596094e-13
        x: [ 1.000e+00  1.000e+01]
      nit: 18
      jac: [-9.101e-07  3.780e-08]
     nfev: 63
     njev: 21
 hess_inv: <2x2 LbfgsInvHessProduct with dtype=float64>
initial point: x0 = [0. 0.]
my BFGS: 
x: [ 1.00000134 10.00001417], iterations: 17
SciPy BFGS: 
  message: Optimization terminated successfully.
  success: True
   status: 0
      fun: 2.6404955478173943e-11
        x: [ 1.000e+00  1.000e+01]
      nit: 16
      jac: [ 1.772e-06 -4.954e-07]
 hess_inv: 

In [23]:
#Rosenbrock's function
xs = np.zeros((5,2))
xs[0,:] = np.array([1.0,-1.2])
xs[1,:] = np.array([2.0,-2.0])
xs[2,:] = np.array([-3.635,5.621])
xs[3,:] = np.array([0.639,-0.221])
xs[4,:] = np.array([1.489,-2.547])

for i in range(5):
    x = xs[i,:]
    print(f'initial point: x0 = {x}')
    print(f'my BFGS: ')
    print(f'x: {mb.BFGS(Rosenbrock,x)[0]}, iterations: {mb.BFGS(Rosenbrock,x)[1]}')
    print(f'SciPy BFGS: ')
    print(scipy.optimize.minimize(Rosenbrock, x, method='BFGS'))
    print(f'SciPy L-BFGS: ')
    print(scipy.optimize.minimize(Rosenbrock, x, method='L-BFGS-B'))

initial point: x0 = [ 1.  -1.2]
my BFGS: 
x: [0.99999969 0.99999938], iterations: 34
SciPy BFGS: 
  message: Optimization terminated successfully.
  success: True
   status: 0
      fun: 6.068590074903568e-12
        x: [ 1.000e+00  1.000e+00]
      nit: 31
      jac: [ 4.783e-06 -7.451e-07]
 hess_inv: [[ 5.054e-01  1.011e+00]
            [ 1.011e+00  2.028e+00]]
     nfev: 123
     njev: 41
SciPy L-BFGS: 
  message: CONVERGENCE: NORM_OF_PROJECTED_GRADIENT_<=_PGTOL
  success: True
   status: 0
      fun: 2.6623148130511254e-13
        x: [ 1.000e+00  1.000e+00]
      nit: 24
      jac: [-5.351e-06  3.331e-06]
     nfev: 90
     njev: 30
 hess_inv: <2x2 LbfgsInvHessProduct with dtype=float64>
initial point: x0 = [ 2. -2.]
my BFGS: 
x: [0.9999981 0.9999962], iterations: 33
SciPy BFGS: 
  message: Desired error not necessarily achieved due to precision loss.
  success: False
   status: 2
      fun: 8.977929510933791e-12
        x: [ 1.000e+00  1.000e+00]
      nit: 43
      jac: [ 6.036e-

In [24]:
#Wood's function
x = np.array([-3.0,-1.0,-3.0,-1.0])
print(f'initial point: x0 = {x}')
print(f'my BFGS: ')
print(f'x: {mb.BFGS(Wood,x)[0]}, iterations: {mb.BFGS(Wood,x)[1]}')
print(f'SciPy BFGS: ')
print(scipy.optimize.minimize(Wood, x, method='BFGS'))
print(f'SciPy L-BFGS: ')
print(scipy.optimize.minimize(Wood, x, method='L-BFGS-B'))

initial point: x0 = [-3. -1. -3. -1.]
my BFGS: 
x: [0.99999987 0.99999975 1.00000004 1.00000009], iterations: 87
SciPy BFGS: 
  message: Optimization terminated successfully.
  success: True
   status: 0
      fun: 5.928997112036049e-13
        x: [ 1.000e+00  1.000e+00  1.000e+00  1.000e+00]
      nit: 90
      jac: [ 2.720e-07 -2.240e-07  1.209e-07 -1.412e-07]
 hess_inv: [[ 1.423e-01  2.826e-01 -1.352e-01 -2.714e-01]
            [ 2.826e-01  5.660e-01 -2.710e-01 -5.439e-01]
            [-1.352e-01 -2.710e-01  1.429e-01  2.842e-01]
            [-2.714e-01 -5.439e-01  2.842e-01  5.709e-01]]
     nfev: 495
     njev: 99
SciPy L-BFGS: 
  message: CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH
  success: True
   status: 0
      fun: 7.876954987871851
        x: [-9.726e-01  9.561e-01 -9.649e-01  9.423e-01]
      nit: 17
      jac: [ 4.688e-04 -1.101e-03 -1.631e-04  1.290e-03]
     nfev: 100
     njev: 20
 hess_inv: <4x4 LbfgsInvHessProduct with dtype=float64>


In [28]:
#Weibull's function
xs = np.zeros((2,3))
xs[0,:] = np.array([5.0,0.15,2.5])
xs[1,:] = np.array([250.0,0.3,5.0])

for i in range(2):
    x = xs[i,:]
    print(f'initial point: x0 = {x}')
    print(f'my BFGS: ')
    print(f'x: {mb.BFGS(Weibull,x)[0]}, iterations: {mb.BFGS(Weibull,x)[1]}')
    print(f'SciPy BFGS: ')
    print(scipy.optimize.minimize(Weibull, x, method='BFGS'))
    print(f'SciPy L-BFGS: ')
    print(scipy.optimize.minimize(Weibull, x, method='L-BFGS-B'))

initial point: x0 = [5.   0.15 2.5 ]
my BFGS: 
x: [50.00080443  1.50000493 24.999972  ], iterations: 53
SciPy BFGS: 
  message: Optimization terminated successfully.
  success: True
   status: 0
      fun: 1.709532083722236e-12
        x: [ 5.000e+01  1.500e+00  2.500e+01]
      nit: 39
      jac: [ 2.686e-09 -7.017e-07 -3.245e-07]
 hess_inv: [[ 6.680e+04  4.093e+02 -2.285e+03]
            [ 4.093e+02  2.536e+00 -1.364e+01]
            [-2.285e+03 -1.364e+01  8.576e+01]]
     nfev: 188
     njev: 47
SciPy L-BFGS: 
  message: CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH
  success: True
   status: 0
      fun: 2.1629462795640744
        x: [ 5.437e+01  1.253e+00  1.539e+01]
      nit: 18
      jac: [-6.010e-02  7.096e+00 -3.879e-01]
     nfev: 88
     njev: 22
 hess_inv: <3x3 LbfgsInvHessProduct with dtype=float64>
initial point: x0 = [250.    0.3   5. ]
my BFGS: 
x: [49.99976862  1.49999857 25.00000785], iterations: 57
SciPy BFGS: 
  message: Optimization terminated successfully.
  s

In [26]:
#Extended Rosenbrock's function
x = -np.ones(100)
ms = np.array([1,3,4,6,7,10,15,20,30,40])
print(f'initial point: x0 = {x}')

for i in range(10):
    m = ms[i]
    print(f'SciPy L-BFGS-B, m = {m}: ')
    print(scipy.optimize.minimize(ExtendedRb, x, method='L-BFGS-B', options = {'maxcor': m}))

print(f'SciPy BFGS: ')
print(scipy.optimize.minimize(ExtendedRb, x, method='BFGS')) 

initial point: x0 = [-1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1.
 -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1.
 -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1.
 -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1.
 -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1.
 -1. -1. -1. -1. -1. -1. -1. -1. -1. -1.]
SciPy L-BFGS-B, m = 1: 
  message: CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH
  success: True
   status: 0
      fun: 7.309226557339343e-10
        x: [ 1.000e+00  1.000e+00 ...  1.000e+00  1.000e+00]
      nit: 51
      jac: [-1.110e-06  1.765e-06 ... -4.441e-06  1.765e-06]
     nfev: 7070
     njev: 70
 hess_inv: <100x100 LbfgsInvHessProduct with dtype=float64>
SciPy L-BFGS-B, m = 3: 
  message: CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH
  success: True
   status: 0
      fun: 1.4514086332795273e-07
        x: [ 9.999e-01  9.999e-01 ...  9.999e-01  9.999e